### PR TITLE
Migration to flutter map v7

### PR DESCRIPTION
**Pull request by Werkaninchen**
**This merge is blocked by the release of [this](https://github.com/rorystephenson/flutter_map_marker_popup/pull/78) flutter_map_marker_popup pr** 

- migrated PolygonOptions isDotted to pattern as the flutter_map Polygon now uses pattern instead of a bool flag for line styling

### CODE REVIEW

**Comment by kallkajxccelerated** [comment]
Are there any updates on when this is expected to be merged?

**Comment by ProgUser145** [comment]
Are there any updates on when can we expect this to be merged?

**Comment by Omario64** [comment]
https://github.com/rorystephenson/flutter_map_marker_popup/pull/78
Merged!

**Comment by Albert221** [comment]
@lpongetti that's ready to merge now :)

**Comment by Omario64** [comment]
It would be great if this gets merged and released soon

**Comment by petodavid** [comment]
Can't wait to see the new release

**Comment by Soap-141** [comment]
I think it's ready now?

**Comment by ProgUser145** [comment]
Can we merge this?

**Comment by nglph** [comment]
any update on merging?

**Comment by MuhammadMusa22** [comment]
Any updates on merging this PR for flutter_map latest dependency.

**Comment by nglph** [comment]
@lpongetti could you give us an outlook?

**Comment by Valou-31** [comment]
Is it possible to merge this PR ?

**Comment by YCdvll** [comment]
@lpongetti go merge pls !

**Comment by leonardo2204** [comment]
Please, merge it :D

**Comment by Soap-141** [comment]
Did someone create a fork of this? I would use it, it's blocking my team's production application, otherwise I might do it soon.

**Comment by Albert221** [comment]
@Soap-141 you may use `dependency_overrides` to unblock yourself and point directly to the ref on this PR's repository

**Comment by DregerTi** [comment]
> Did someone create a fork of this? I would use it, it's blocking my team's production application, otherwise I might do it soon.

If you want https://github.com/DregerTi/flutter_map_marker_cluster

**Comment by ProgUser145** [comment]
It feels like this library is not being actively maintained anymore. @lpongetti can you give us an update if that is the case?

**Comment by DHamitiOP** [comment]
Removing Stale label

**Comment by TheotimeSlow** [comment]
Remove stale label

**Pull request merged**
