### PR TITLE
Bump flutter map 1.0.0

### LINKED ISSUE #119: Bump flutter_map to 1.0.0
Bump flutter_map dependency to the latest version

### PR DESCRIPTION
**Pull request by pablojimpas**
Closes #119 

Don't be afraid about all the changes: I branched off from @rorystephenson's work on https://github.com/lpongetti/flutter_map_marker_cluster/pull/117 to avoid later conflicts when merging.

This is mostly the same stuff that I've already done in https://github.com/rorystephenson/flutter_map_marker_popup/pull/45.

Note that while I was here I've also added and fixed the same static analysis rules that were introduced recently to `flutter_map` itself, they are stricter and the changes might bring some performance improvements alongside the refactoring work made already by Rory.

Note: Review and merge #117 first
Note 2: There is still work to do in order to release a new version: update de changelog accordingly and bump this package's version in the `pubspec.yaml`.

### CODE REVIEW

**Comment by RicardoRB** [comment]
It would be awesome to have this :)

**Comment by jithware** [comment]
@lpongetti I would love to have this pull request merged as well. Using your awesome plugin in [mappoff](https://github.com/jithware/mappoff)

**Comment by RicardoRB** [comment]
As a temporal solution:

  flutter_map_marker_cluster:
    git:
      url: https://github.com/pablojimpas/flutter_map_marker_cluster.git
      ref: bump-flutter_map-1.0.0

**Comment by TitanKing** [comment]
Thanks for taking care of this! Much appreciated!

**Pull request merged**
