### PR TITLE
Migrate to flutter_map 3

### LINKED ISSUE #134: Flutter Map v3.0.0-beta support?
The new beta v.3.0.0 got released. Can you please add support for it?

### LINKED ISSUE #138: `flutter_map` 3.0.0 dependency error
`flutter_map` just released the stable 3.0.0 version.
However when we try to upgrade it to the latest version along with `flutter_map_marker_cluster` `0.5.4` we get this error;

> Because flutter_map_marker_cluster 0.5.4 depends on flutter_map ^2.2.0 and no versions of flutter_map_marker_cluster match >0.5.4 <0.6.0, flutter_map_marker_cluster ^0.5.4 requires flutter_map ^2.2.0.

### PR DESCRIPTION
**Pull request by MooNag**
Dependencies are updated.

Fixes #138
Fixes #134

fleaflet/flutter_map#1333

### CODE REVIEW

**Comment by aytunch** [comment]
@MooNag I don't see an open PR in flutter_map. What does this PR accomplish? I see lots of refactoring. Aside of that what is new? An explanation would be perfect. Also they are looking for maintainers if you are interested.

**Comment by MooNag** [comment]
Commenting to remove stale tag

**Comment by aytunch** [comment]
@lpongetti Hi. Can you please accept this PR?
@MooNag thanks for this btw :)

**Comment by kamami** [comment]
Please merge this :)

**Pull request merged**
