### PR TITLE
Changed flutter_map to 0.8.0 to enable the plugin with current flutter version

### PR DESCRIPTION
**Pull request by Dev-Owl**
See issue #25

### CODE REVIEW

**Comment by pro100svitlo** [comment]
Please, merge this one asap 🙏

**Comment by agnoam** [comment]
What about the `pub.dev` dependency ?

**Comment by Dev-Owl** [comment]
@agnoam What do you mean ? I just adjusted the dependency for the code to work again. If somebody needs this now, clone my repo and add a local reference to the package in your code like this:
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    path: ../flutter_map/
  flutter_map_marker_cluster:
    path: ../markercluster/
```
Please adjust the path to reflect your local setup

**Comment by agnoam** [comment]
I don't need that now. I'm asking when you will update the `pub.dev` dependency ?

**Comment by Dev-Owl** [comment]
I'm not the owner of this repo, I can't simply update the published package. We have to wait for the actual owner to make a new release and update the published package.

**Comment by pro100svitlo** [comment]
@lpongetti 🙏 😉

**Comment by bameda** [comment]
A workarround: overwrite the dependencie in `pubspec.yaml` 

```yaml
dependencies:
  (...)
  flutter_map: ^0.8.0
  flutter_map_marker_cluster: ^0.2.5
  (...)

dependency_overrides:
  flutter_map: ^0.8.0

```

More info [here] (https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution)

And I think this PR is similar to https://github.com/lpongetti/flutter_map_marker_cluster/pull/27

**Comment by soromamadou** [comment]
Hi, now flutter_map is at 0.8.1

**Comment by lpongetti** [comment]
updated to 0.8.2

**Pull request closed without merging**
