### PR TITLE
Add support for newest version of flutter_map dep

### PR DESCRIPTION
**Pull request by robertpiosik**
There is a new version `^0.11.0` which has vast improvements. My suggestion is to support up to major change if there are no contraindications I'm not aware of.

### CODE REVIEW

**Review by jakobkuehne — APPROVED** [review]

**Comment by icangku** [comment]
please approve this

**Review by icangku — APPROVED** [review]

**Comment by robertpiosik** [comment]
I don't know how to reach out to @lpongetti :(

Without it, the plugin fails with newer version of `flutter_map`.

As a workaround one can add a fork to a pubspec.

**Comment by HugoHeneault** [comment]
Have you tried using [`dependency_overrides`](https://dart.dev/tools/pub/dependencies#dependency-overrides) ?

**Comment by icangku** [comment]
i have already used the robertpiosik:patch-1 branch, using git option in pubspeck.yml

**Comment by quizact** [comment]
I need to access git@github.com:robertpiosik/flutter_map_marker_cluster.git. How can I do this?

**Comment by robertpiosik** [comment]
@quizact as this is merged, you should use the original repo now

**Pull request merged**
