### PR TITLE
Upgrade flutter_map v4

### PR DESCRIPTION
**Pull request by nploi**
Hi @lpongetti, i want upgrade flutter_map v4, please help me review this PR.

- I convert to draft, because we need wait for this [PR](https://github.com/rorystephenson/flutter_map_marker_popup/pull/59) before.

Thank you 🙏

### CODE REVIEW

**Comment by nploi** [comment]
I'm tested on example:

https://user-images.githubusercontent.com/34020090/236607457-8eeb639c-4221-4178-af2d-b57343d60b9e.mov

run tests passed:
```
flutter test     
00:02 +9: All tests passed!                                                                     
```

**Comment by nploi** [comment]
> I convert to draft, because we need wait for this https://github.com/rorystephenson/flutter_map_marker_popup/pull/59 before.

They merged.

**Review by moritzdawo — APPROVED** [review]

**Review by SalihCanBinboga — APPROVED** [review]

**Comment by jannisnikoy** [comment]
Would be nice to get this PR merged 👍

**Comment by thoKling** [comment]
+1 would be really nice to merge this one !

**Comment by jannisnikoy** [comment]
Same here. On an active project I updated our pubspec to the fork by @nploi for now, works like a charm 👌

**Comment by BrianCraig** [comment]
Also can confirm @lpongetti, no problems while using the Fork on an app, I also can notice better performance overall (100K markers usage).

**Pull request merged**
